stages:
  - test
  - build
  - deploy

django tests:
  stage: test
  image: python:3-alpine
  script:
    - pip install -r requirements.txt
    - python manage.py test
  tags:
    - docker

docker build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG} .
    - docker push ${CI_REGISTRY_IMAGE}
  tags:
    - docker

deploy to prod:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker pull ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
    - docker rm -f permkrovlya || true
    - docker run -d -p 81:81 -n permkrovlya ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
  tags:
    - docker