name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: python:3-alpine
    steps:
    - uses: actions/checkout@v1
    - name: Run Django tests
      run:  python manage.py
      
      
  build:
    runs-on: docker:stable
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login -u ${{ secrets.GITLAB_USER }} -p ${{ secrets.GITLAB_USER }}
        docker build . --file Dockerfile --tag ${{ secrets.GITLAB_REGISTRY }}:${{ GITHUB_REF_NAME }}
        docker push ${{ secrets.GITLAB_REGISTRY }}
